# Generated by Django 3.1.7 on 2021-04-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='referralCode',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
